version: "3"
services:
  openresty:
    image: openresty/openresty:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/logs:/usr/local/openresty/nginx/logs
      - ./nginx/html:/usr/local/openresty/nginx/html
      - ./nginx/cert:/usr/local/openresty/nginx/cert
      - ./nginx/run:/var/run/openresty
      - ./nginx/lua:/usr/local/openresty/nginx/lua
    ports:
      - "80:80"
  minio1:
    image: "quay.io/minio/minio:RELEASE.2023-09-07T02-05-02Z"
    container_name: minio
    ports:
      - "9000:9000"
      - "19090:19090"
    volumes:
      - "./minio/data/1:/data"
    command: server /data --console-address ":19090"
    environment:
      MINIO_ROOT_USER: thk_im
      MINIO_ROOT_PASSWORD: thk_im_mino
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
