version: "3"
services:
  minio1:
    image: "quay.io/minio/minio:RELEASE.2023-09-07T02-05-02Z"
    container_name: minio
    ports:
      - "19000:9000"
      - "19090:9090"
    volumes:
      - "./data/1:/data"
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: thk_im
      MINIO_ROOT_PASSWORD: thk_im_mino
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3